@localhost = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NTI4OTU3MTl9.eX0nCvYdmKhN8BzDsFwx1noQYDhOJ14OVsE8WrpEPpc

### Throw Create
POST {{localhost}}/throws
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "training_id": 1,
  "points": 5
}

### Throw Update
PATCH {{localhost}}/throws/38
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "training_id": 1,
  "points": 3
}

### Throw Destroy
DELETE {{localhost}}/throws/38
Authorization: Bearer {{ jwt }}
Content-Type: application/json


### Training Index
GET {{localhost}}/trainings
Authorization: Bearer {{ jwt }}
Content-Type: application/json

### Training Create
POST {{localhost}}/trainings
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "test training"
}

### Training Destroy
DELETE {{localhost}}/trainings/12
Authorization: Bearer {{ jwt }}
Content-Type: application/json


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Users show
GET {{localhost}}/users/3
Authorization: Bearer {{ jwt }}
Content-Type: application/json

### Users update
PATCH {{localhost}}/users/3
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "Testingly"
}

### Users Destroyyyy
DELETE {{localhost}}/users/3
Authorization: Bearer {{ jwt }}
Content-Type: application/json